name: CI
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Github page 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 15.x
      - name: Install package and build 🏗
        run: |
          yarn install
          yarn run build
      - name: Run test 🧪
        run: |
          echo No test case written here
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: pepo.dev
